plugins {
    id 'java'
    id 'application'
}

group = 'ru.egor'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.esotericsoftware:kryo:5.6.2'
    implementation 'org.apache.parquet:parquet-hadoop:1.18.1'
    implementation 'org.apache.hadoop:hadoop-common:3.5.0'
    implementation 'org.apache.hadoop:hadoop-mapreduce-client-core:3.5.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'ru.egor.Main'
}

test {
    useJUnitPlatform()
}
